package com.portfolio.assetory.review.service;
import org.springframework.data.domain.PageRequest; import org.springframework.data.domain.Sort; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.portfolio.assetory.access.repository.ProductAccessRepository; import com.portfolio.assetory.global.exception.BusinessException; import com.portfolio.assetory.global.exception.ErrorCode; import com.portfolio.assetory.product.domain.ProductImageType; import com.portfolio.assetory.product.repository.ProductImageRepository; import com.portfolio.assetory.review.domain.Review; import com.portfolio.assetory.review.dto.request.CreateReviewRequest; import com.portfolio.assetory.review.dto.request.UpdateReviewRequest; import com.portfolio.assetory.review.dto.response.MyReviewListResponse; import com.portfolio.assetory.review.dto.response.MyReviewResponse; import com.portfolio.assetory.review.repository.ReviewRepository;
@Service @Transactional public class ReviewCommandService {
	private final ProductAccessRepository accessRepository; private final ReviewRepository reviewRepository; private final ProductImageRepository imageRepository;
	public ReviewCommandService(ProductAccessRepository accessRepository, ReviewRepository reviewRepository, ProductImageRepository imageRepository) { this.accessRepository=accessRepository; this.reviewRepository=reviewRepository; this.imageRepository=imageRepository; }
	public MyReviewResponse create(Long userId, Long productId, CreateReviewRequest request) { var access=accessRepository.findActiveByUserIdAndProductId(userId,productId).orElseThrow(()->new BusinessException(ErrorCode.FORBIDDEN)); if(reviewRepository.existsByWriterIdAndProductId(userId,productId)) throw new BusinessException(ErrorCode.REVIEW_ALREADY_EXISTS); return MyReviewResponse.from(reviewRepository.save(Review.create(access.getOrderItem().getId(), access.getOrderItem().getOrder().getBuyer(), access.getOrderItem().getProduct(), request.rating(), request.content()))); }
	public MyReviewResponse update(Long userId, Long reviewId, UpdateReviewRequest request) { if(request.rating()==null&&request.content()==null) throw new BusinessException(ErrorCode.INVALID_INPUT); var review=owned(userId,reviewId); review.update(request.rating(),request.content()); return MyReviewResponse.from(review); }
	public void delete(Long userId, Long reviewId) { owned(userId,reviewId).delete(); }
	@Transactional(readOnly=true) public MyReviewListResponse list(Long userId,int page,int size) { if(page<0||size<1||size>100) throw new BusinessException(ErrorCode.INVALID_INPUT); var reviews=reviewRepository.findActiveByWriterId(userId,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt"))); var thumbnails=imageRepository.findThumbnailsByProductIds(reviews.getContent().stream().map(r->r.getProduct().getId()).toList(),ProductImageType.THUMBNAIL).stream().collect(java.util.stream.Collectors.toMap(image->image.getProductId(),image->image.getImageUrl(),(first,ignored)->first)); return MyReviewListResponse.from(reviews,thumbnails); }
	private Review owned(Long userId,Long reviewId) { var review=reviewRepository.findActiveById(reviewId).orElseThrow(()->new BusinessException(ErrorCode.REVIEW_NOT_FOUND)); if(!review.getWriter().getId().equals(userId)) throw new BusinessException(ErrorCode.FORBIDDEN); return review; }
}
